#!/usr/bin/python
#
import sys
import getopt

from rpclite.server import *

def usage():
    print >>sys.stderr, "usage: any_server [-b|t|f] [<address> <port>]"
    print >>sys.stderr, "    -b: 'blocking', -t: 'threading', -f: 'forking'"
    sys.exit(2)

server = XMLRPCServer

# handle options
opts,args = getopt.getopt( sys.argv[1:], 'btfh' )    
for k,v in opts:
  if k == '-h': usage()
  elif k == '-b': server = BlockingXMLRPCServer
  elif k == '-t': server = ThreadingXMLRPCServer
  elif k == '-f': server = ForkingXMLRPCServer
  
try:
    addr = args[0], int(args[1])
except IndexError:
    addr = "localhost", 8021

server = server('any_server', addr)
try:
    server.serve_forever()
except KeyboardInterrupt:
    pass

