#!/usr/bin/python
#
import sys
import time

from rpclite.server import *

try:
    addr = sys.argv[1], int(sys.argv[2])
except IndexError:
    addr = "localhost", 8021


def bad_ping(data):
    if int(data[0])%2 == 0:
        print '+++ sleeping +++'
        time.sleep(5)
    return data

server = XMLRPCServer('bad_ping_server', addr)

# overwrite system ping
server.register_function(bad_ping, 'system.ping')

try:
    server.serve_forever()
except KeyboardInterrupt:
    pass
