#!/usr/bin/python
#
import sys
from rpclite.server import XMLRPCServer

try:
    addr = sys.argv[1], int(sys.argv[2])
except IndexError:
    addr = "localhost", 8021


def echo(data):
    return data

server = XMLRPCServer('echo_server', addr)    
server.register_function(echo)    

try:
    server.serve_forever()
except KeyboardInterrupt:
    pass
