#!/usr/bin/python
#
import sys

import rpclite as rpc
from rpclite.server import XMLRPCServer

try:
    addr = sys.argv[1], int(sys.argv[2])
except IndexError:
    addr = "localhost", 8021


def send_file(name, buf):
    fp = open(name, 'wb')
    buf = buf.data
    fp.write(buf)
    fp.close()
    return True

def get_file(fn):
    fp = open(fn, 'rb')
    buf= fp.read()
    fp.close()
    return (rpc.Binary(buf))

server = XMLRPCServer('file_server', addr)    
server.register_function(send_file)    
server.register_function(get_file)    

try:
    server.serve_forever()
except KeyboardInterrupt:
    pass
