#!/usr/bin/python
#
import sys

from rpclite.server import XMLRPCServer

try:
    addr = sys.argv[1], int(sys.argv[2])
except IndexError:
    addr = "localhost", 8021


def sleep(dt):        
    import time
    print '+++ sleeping +++ ...'
    sys.stdout.flush()
    time.sleep(dt)
    print '+++ woke up +++'
    sys.stdout.flush()
    return 1

server = XMLRPCServer('timeout_server', addr)
server.register_function(sleep)    

try:
    server.serve_forever()
except KeyboardInterrupt:
    pass
