#!/usr/bin/python
#
import sys
import time

import rpclite as rpc
    
try:
    url = sys.argv[1]
except IndexError:
    url = "http://localhost:8021"


server = rpc.XMLRPCServerProxy(url)

print 'sending sleep'

try:
    server.sleep(10, timeout=2)
except rpc.SocketTimeout:
    print '+++ timeout +++'

while 1:
    try:
        print 'is server alive ? ...', server.system.ping('yep')
        time.sleep(0.5)
    except KeyboardInterrupt:
        break
