#!/usr/bin/python
#
import sys

import rpclite as rpc
    
try:
    url = sys.argv[1]
except IndexError:
    url = "http://localhost:8021"


server = rpc.XMLRPCServerProxy(url)

server.do_exception()
    
