#!/usr/bin/python
#
import sys
from rpclite.server import XMLRPCServer

try:
    addr = sys.argv[1], int(sys.argv[2])
except IndexError:
    addr = "localhost", 8021


def do_exception():
    string.split('123')
    #2/0

server = XMLRPCServer('traceback_server', addr)
server.register_function(do_exception)

try:
    server.serve_forever()
except KeyboardInterrupt:
    pass
